name: marketing_dashboard
description: Teamply - Marketing Dashboard for Funnel, ROI, KPI, Campaign Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: 6.1.5+1
  shared_preferences: 2.5.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  fl_chart: 0.69.0
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  # 보안 & 세션
  crypto: ^3.0.3
  uuid: ^4.5.1
  web: ^1.1.1
  # Firebase
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  cloud_firestore: 5.4.3
  google_mobile_ads: 5.3.1
  webview_flutter: 4.13.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: 2.0.1
  build_runner: 2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
